### ISSUE TITLE
Error while executing complexity()

### ISSUE THREAD

**Issue by sawan16** [lpfgarcia/ECoL#47]
>` complexity(Species ~., iris)`
Error in complexity.default(modFrame[, -1, drop = FALSE], modFrame[, 1,  : 
  argument "type" is missing, with no default

**Comment by lpfgarcia** [comment]
Hi sawan16

This error is because you are using the CRAN version (0.2.0) of the package and not the develop version (0.3.0). In the 0.2.0 version, the type parameter is required. In the 0.3.0 version, it is not necessary anymore. I recommend you follow the Reference manual (https://cran.r-project.org/web/packages/ECoL/ECoL.pdf) otherwise install the develop version  (https://github.com/lpfgarcia/ECoL#installation)

**Comment by sawan16** [comment]
Thanks a lot for your help. I have Installed the **dev** version. Now its running.
